### ISSUE TITLE
插件安装后，登录页没有“gitlab登录”按钮

### ISSUE THREAD

**Issue by jicro** [cyj0122/yapi-plugin-gitlab#6]
按照教程配置和安装插件后，通过gitlab测试，SystemHook已经可用（状态码200），但是经查看Response后发现实际是：`{"errcode":40011,"errmsg":"请登录...","data":null}`
![image](https://user-images.githubusercontent.com/22854743/53872570-84647380-4039-11e9-98be-2230ed90494f.png)

尝试直接访问http://IP:PORT/api/plugin/oauth2/callback也能访问到，但是登录页没有“gitlab登录”的按钮。
YApi日志也未见报错，但是我查看了vendors/plugin.json发现如下：
`[
  {
     "title": "yapi-plugin-qsso",
     "url": "https://github.com/ymfe/yapi-plugin-qsso",
     "desc": "qunar 专用 sso 第三方登录"
  },
  {
     "title": "yapi-plugin-import-openapi",
     "url": "https://github.com/yuu2lee4/yapi-plugin-import-openapi",
     "desc": "openapi导入插件(仅支持3.0)"
  }
]
`

是否我的安装有问题？

Yapi-1.5.6    Gitlab-11.6.2

@cyj0122

**Comment by cyj0122** [comment]
请参考文档第四步配置，可以的话发一下yapi config.json配置。

**Comment by jicro** [comment]
> 请参考文档第四步配置，可以的话发一下yapi config.json配置。

@cyj0122 
如下图所示，其中xxx.98:8090为gitlab的地址，xxx.97:3000为YApi的地址，accessToken是gitlab上root用户的口令。
![image](https://user-images.githubusercontent.com/22854743/53933059-9268d180-40d7-11e9-8d7c-b2a82ec5549b.png)

**Comment by WKlili** [comment]
同没有按钮--

**Comment by WKlili** [comment]
配置完需要执行npm run build-client。sorry，已解决

**Comment by cyj0122** [comment]
开发模式下可参考https://yapi.ymfe.org/documents/plugin-dev.html

**Comment by damonsuo** [comment]
同样的问题，按照教程配置和安装插件后，通过gitlab测试，SystemHook已经可用（状态码200），但是经查看Response后发现实际是：{"errcode":40011,"errmsg":"请登录...","data":null}
请问是什么原因导致的？如何解决？ @cyj0122

**Comment by mrfmrf** [comment]
@jicro 你的问题弄好了吗

**Comment by xyjwsj** [comment]
同没有按钮--
